Repository vladgh/ansible-collection-vladgh-samba, pull requests merged in 2023-05, with the labels that each got.

#73 Archlinux fixes
  roles/server/vars/os_Archlinux.yml
Labels: refactor

#75 Remove unnecessary file path comments
  roles/server/defaults/main.yml
  roles/server/handlers/main.yml
  roles/server/tasks/main.yml
  roles/server/vars/os_Archlinux.yml
  roles/server/vars/os_Debian.yml
  roles/server/vars/os_RedHat.yml
Labels: refactor

#78 Consistent `samba_map_to_guest`
  README.md
  roles/server/defaults/main.yml
Labels: documentation, refactor

#81 Consistent code blocks
  README.md
Labels: documentation

#82 Prefer `include_role`
  playbooks/samba.yml
Labels: refactor

#83 Migrate from `with_X` to `loop`
  roles/server/handlers/main.yml
  roles/server/tasks/main.yml
Labels: refactor

#84 Improve conditionals
  README.md
  roles/server/tasks/main.yml
  roles/server/templates/smb.conf.j2
  roles/server/templates/smbusers.j2
Labels: refactor

#85 Add support for Fedora 38
  .github/workflows/test.yml
  roles/server/meta/main.yml
Labels: refactor
