Repository vladgh/ansible-collection-vladgh-samba, pull requests merged in 2025-02, with the labels that each got.

#200 feat: add var for extra global config options
  README.md
  roles/server/templates/smb.conf.j2
Labels: stale

#187 Documentation enhancements (Typos, Links, Punctuation, Formatting)
  README.md
  roles/server/README.md
  roles/server/templates/smb.conf.j2
Labels: documentation

#217 Update Fedora test version
  .github/workflows/test.yml
Labels: refactor
